version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      PB_GO: 'true'
      # PBRP_BRANCH: 'android-9.0'
      VERSION: '2.9.0'
      VENDOR: 'Itel'
      CODENAME: 'I805'
      # EXTRA_CMD: "cd device/$VENDOR/$CODENAME; apt-get -qqy update; apt-get -qqy install dos2unix; dos2unix *;"
      BUILD_LUNCH: 'omni_I805-userdebug'
      TEST_BUILD: 'true'
      # USE_NINJA: 'true'
    working_directory: /home/builder/pitchblack
    steps:
      # - checkout
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://gist.github.com/rokibhasansagar/62f90b84f5de4fcb3b1313096710b1aa/raw/build.sh
            chmod a+x build.sh
            source build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: personal-envs
